name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  # Optional: Bei Tags, z. B. v21.0.1
  # tags:
  #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./patched-dolibarr-image
          push: true
          tags: yourdockerhubuser/dolibarr-custom:21.0.1
          build-args: |
            BASE_TAG=21.0.1
